# Generated by Django 4.2.4 on 2023-08-28 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="authors",
        ),
    ]
