# Generated by Django 4.2.4 on 2023-08-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowings",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
