# Generated by Django 4.2.4 on 2023-08-28 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_rename_author_book_authors"),
        ("borrowings", "0002_alter_borrowings_actual_return_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Borrowings",
            new_name="Borrowing",
        ),
    ]
